### ISSUE TITLE
Report about parsing errors and warnings with detailed info in `oapi3ts ` (cause, place in OAS structure, related refs)

### ISSUE THREAD

**Issue by johnthecat** [koshevy/codegena#13]
There is no way to find out in which struct in contract happened error.
[@babel/code-frame](https://babeljs.io/docs/en/babel-code-frame) can be used.

**Comment by koshevy** [comment]
@johnthecat  There is no case to use `@babel/code-frame` and something like AST. These things intended to be used for:

- To parse syntax of JS/JSON before it get turned into a object
- To inform where syntax mistake is located

This library is not JSON parser and deal with already converted data structure. The place where error located can be highlighted using JSON pointer.

----

The problem is in that `oapi3ts` very poor on checks and any information output. And so I started to work on this problem.

**Comment by koshevy** [comment]
This moment most of throwing errors have [attached meta info](https://github.com/koshevy/codegena/blob/master/libs/oapi3ts/src/lib/core/parsing-problems.ts#L9) can help to find place where and why error had occurred.

You can handle an error and retrieve meta information:

```typescript
var cliLib = require('@codegena/oapi3ts-cli');
var cliApp = new cliLib.CliApplication;
var { ParsingError } = require('@codegena/oapi3ts');

try {
  cliApp.createTypings();
  cliApp.createServices('angular');
} catch(error) {
  if (error instanceof ParsingError) {
    // ... handle ParsingError
  }
}
```
So, if property `jsonPath` is set, you can find place in OAS-structure, where parsing stuck (could be decoded via [json-pointer](https://www.npmjs.com/package/json-pointer)). And using `schema`/`relatedRef`/`descriptors` properties you can understand — what places are associated with descriptors was in converting/rendering.

Next steps are supposed to be:

1. You can find place with error in AST (use [json-to-ast](https://www.npmjs.com/package/json-to-ast)). So you can localize start pointers.
2. After, you can output your JSON using [cardinal](https://www.npmjs.com/package/cardinal) with highlight.
