### ISSUE TITLE
enum type as a schema

### ISSUE THREAD

**Issue by stepanzabelin** [koshevy/codegena#29]
OAS allows Enum type to be described as a schema
https://swagger.io/docs/specification/data-models/enums/
Enum's description structure is almost the same
May you implement this feature?

**Comment by koshevy** [comment]
@stepanzabelin Thank you for issue!

Feature you're tell about  is already implemented, but something goes wrong. As it supposed, [$ref](https://github.com/koshevy/codegena/commit/03602fef7c9629be9064c084129751eaade23e51#diff-df63d1a035181f0089da284185b882cbR29) to the [named enum](https://github.com/koshevy/codegena/commit/03602fef7c9629be9064c084129751eaade23e51#diff-df63d1a035181f0089da284185b882cbR61), should drive appearing new data type `NamedEnum`.

But as it turns out, named enum doesn't appear and there inline enum is using instead:

```
/**
 * Model of parameters for API `/`
 */
export interface SimplestGet01Parameters {
    /**
     * Important query parameter
     */
    importantProperty: string;
    /**
     * Named enum will be transformed to a named data-type
     */
    optionalProperty?: 'first-value' | 'second-value' | 'third-value';
}
```

And no `NamedEnum` model was created. This is bug.

**Comment by koshevy** [comment]
@stepanzabelin Fixed in [last published version](https://github.com/koshevy/codegena/commit/4cc99264e900fb6937671fadcf022a58ac972c8c).

**Comment by stepanzabelin** [comment]
Thank you @koshevy
I've checked, it works now
